global:
  scrape_interval: 15s


scrape_configs:
  - job_name      : "prometheus"
    static_configs:
      - targets: ["localhost:9090"]


#  - job_name      : "ubuntu-servers"
#    static_configs:
#      - targets:
#          - 0.0.0.1:9100
#          - 0:0.0.2:9100
